<?php
declare(strict_types=1);

namespace app\widgets;

use yii\base\Widget;

class CommentsWithAnswerField extends Widget
{
    public $commentForm = [];

    public $comments = [];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('comments', ([
            'commentForm' => $this->commentForm,
            'comments' => $this->comments,

        ]));
    }

}


